# SPDX-FileCopyrightText: 2024 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-on-approval:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON File
        id: curling-reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Fetch the reviews and place them into a json file.
          curl -o reviews.json -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews

      - name: Check for Approvals
        id: check-approvals
        run: |
          # Count the number of approvals
          APPROVALS=$(jq '[.[] | select(.state=="APPROVED")] | length' reviews.json)

          echo "Number of approvals: $APPROVALS"
          echo "::set-output name=approvals::$APPROVALS"

      - name: Add Approved Label if Enough Approvals
        if: steps.check-approvals.outputs.approvals >= 2  # Change the threshold here
        uses: actions-ecosystem/action-add-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: "S: Approved"

      - name: Remove Other Labels on Approved
        if: steps.check-approvals.outputs.approval >= 2
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: |
            "S: Needs Review"
            "S: Needs Second Approval"

      - name: Add Second Approval Requirement on Approval
        if: steps.check-approvals.outputs.approvals == 1
        uses: actions-ecosystem/action-add-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: |
            "S: Needs Second Approval"
            "S: Needs Review"

      - name: Remove Other Labels on Second Approval Requirement
        if: steps.check-approvals.outputs.approvals == 1
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: "S: Approved"

      - name: Remove All Other Labels if No Approval
        if: steps.check-approvals.outputs.approvals < 1
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: |
            "S: Approved"
            "S: Needs Second Approval"
