name: Review Trigger

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is so incredibly fucking stupid"
