name: "Labels: Approved"

on:
  workflow_run:
    workflows: ["Review Trigger"]
    types: [completed]

jobs:
  label-on-approval:
    if: github.event.workflow_run.event == 'pull_request_review'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Extract PR number
        id: pr
        run: |
          PR_NUMBER=$(jq '.workflow_run.pull_requests[0].number' "$GITHUB_EVENT_PATH")
          echo "pr=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Create JSON File
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr.outputs.pr }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          curl -o reviews.json -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER/reviews

      - name: Check for Approvals
        id: check-approvals
        run: |
          APPROVALS=$(jq '
          group_by(.user.login)
          | map(last)
          | map(select(.state=="APPROVED"))
          | length
          ' reviews.json)

          echo "Number of approvals: $APPROVALS"
          echo "approvals=$APPROVALS" >> $GITHUB_OUTPUT
  
      - name: Add Approved Label if Enough Approvals
        if: steps.check-approvals.outputs.approvals >= 2
        uses: actions-ecosystem/action-add-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ steps.pr.outputs.pr }}
          labels: "S: Approved"

      - name: Remove Other Labels on Approved
        if: steps.check-approvals.outputs.approvals >= 2
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ steps.pr.outputs.pr }}
          labels: |
            "S: Needs Review"
            "S: Needs Second Approval"

      - name: Add Second Approval Requirement on Approval
        if: steps.check-approvals.outputs.approvals == 1
        uses: actions-ecosystem/action-add-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ steps.pr.outputs.pr }}
          labels: |
            "S: Needs Second Approval"
            "S: Needs Review"

      - name: Remove Other Labels on Second Approval
        if: steps.check-approvals.outputs.approvals == 1
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ steps.pr.outputs.pr }}
          labels: "S: Approved"

      - name: Remove Other Labels if No Approval
        if: steps.check-approvals.outputs.approvals < 1
        uses: actions-ecosystem/action-remove-labels@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ steps.pr.outputs.pr }}
          labels: |
            "S: Approved"
            "S: Needs Second Approval"
